// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetTest.Models;

#nullable disable

namespace dotnetTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220411182919_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("dotnetTest.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("componentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("massFlowrateKgPerS")
                        .HasColumnType("double");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("pressurePa")
                        .HasColumnType("double");

                    b.Property<double>("temperatureC")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("componentCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
